<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{
	public function setUp() {
		$this->actAs('Searchable', array('fields' => array('username')));
	  	$this->hasMany('Artist', array('local' => 'user_id',         // <- these are the column names
	                                      'foreign' => 'artist_id',      // <- in the association table
	                                      'refClass' => 'UserArtist'));  // <- the following line is needed in many-to-many relations
		$this->hasMany('Album', array('local' => 'user_id',         // <- these are the column names
	                                      'foreign' => 'album_id',      // <- in the association table
	                                      'refClass' => 'UserAlbum'));  // <- the following line is needed in many-to-many relations
	}
}