package com.artistalert.offline.displaytest;



/**
 * 
 * @author Charlie
 * 
 * modified to test sending data between frames
 * @author Woojoon
 * 
 */
public class UI_Scan extends javax.swing.JFrame {

	private String directory;
	
	/** Creates new form scan_ui */
	public UI_Scan() {
		initComponents();
	}
	/** TEST constructor w/ directory as argument */
	public UI_Scan(String directory) {
		initComponents();
		this.directory = directory;
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonChoose = new javax.swing.JButton();
		buttonScan = new javax.swing.JButton();
		barProgress = new javax.swing.JProgressBar();
		labelDirectory = new javax.swing.JLabel();
		labelProgress = new javax.swing.JLabel();
		buttonExit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		buttonChoose.setText("Choose Directory");
		buttonChoose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonChooseActionPerformed(evt);
			}
		});

		buttonScan.setText("Scan");
		buttonScan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonScanActionPerformed(evt);
			}
		});

		labelDirectory.setText("Directory Chosen");

		labelProgress.setText("Scanning x/y");

		buttonExit.setText("Exit");
		buttonExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonExitActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(23, 23, 23)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				labelProgress,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				92,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				buttonChoose)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				buttonScan))
																														.addComponent(
																																labelDirectory,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																180,
																																Short.MAX_VALUE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												buttonExit)
																										.addGap(
																												33,
																												33,
																												33))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												barProgress,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												274,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																		.addGap(
																				27,
																				27,
																				27)))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																buttonChoose)
														.addComponent(
																buttonScan)
														.addComponent(
																buttonExit))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(labelDirectory)
										.addGap(26, 26, 26)
										.addComponent(
												barProgress,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(labelProgress)
										.addContainerGap(50, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonChooseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonChooseActionPerformed

		// Choose directory code here

	}// GEN-LAST:event_buttonChooseActionPerformed

	private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonExitActionPerformed

		// just a test, Remove for actual code
		System.exit(0);

	}// GEN-LAST:event_buttonExitActionPerformed

	private void buttonScanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonScanActionPerformed

		// just a test, Remove for actual code
		barProgress.setValue(75);
		
		/**
		 * Test display - loads a UI_Result with Reader class
		 *  
		 */
		final Reader reader = new Reader(this.directory);
		new UI_Results(reader.scan()).setVisible(true);

	}// GEN-LAST:event_buttonScanActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final String args[]) {
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UI_Scan(args[0]).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JProgressBar barProgress;
	private javax.swing.JButton buttonChoose;
	private javax.swing.JButton buttonExit;
	private javax.swing.JButton buttonScan;
	private javax.swing.JLabel labelDirectory;
	private javax.swing.JLabel labelProgress;
	// End of variables declaration//GEN-END:variables

}
