<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserArtist extends BaseUserArtist
{
  public function setUp() {
  	$this->hasOne('Artist as Artist', array('local' => 'artist_id',
                                                    'foreign' => 'artist_id'));
    $this->hasOne('User as User', array('local' => 'user_id',
                                                    'foreign' => 'user_id'));
  }

}