<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{
	public function setUp() {
		$this->actAs('Searchable', array('fields' => array('username')));
	}
}